### ISSUE TITLE
Add X-Ray Spectroscopy Coverage

### ISSUE THREAD

**Issue by acraugh** [pds-data-dictionaries/ldd-spectral#7]
Dr. Thomas Cornet (ESA/ESAC, BepiColombo project) has requested adding X-Ray spectra to the coverage of the Spectral Dictionary. The structures and concepts are parallel to those for the ranges already covered, but the bins are measured in eV.

This would require extending the parallel definitions that currently include wavelength, wave number, and frequency to units of energy, adding the corresponding validation constraints, generating additional regression test scenarios, and updating the documentation.

**Comment by jordanpadams** [comment]
Transferred to pds-data-dictionaries/PDS4-LDD-Issue-Repo#12
